#spring.application.name=householdAccount
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=Serigaya
#spring.jpa.open-in-view=True

spring.application.name=householdAccount
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Serigaya
spring.jpa.open-in-view=True

 
#spring:
#  datasource:
#    sqlScriptEncoding: UTF-8
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    username:postgres
#    password: Serigaya
# 
#  jpa:
#    hibernate:
#      ddl-auto: update
#    
#   
#logging:
#  level:
#    sql: debug
# 